---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenant-sync
  namespace: tenant-appteam
spec:
  interval: 10m0s
  path: ./apps/k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: tenant-repo

