---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tenant-repo
  namespace: tenant-infrastructure
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Foundato/gitops-example-infrastructure

