---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
  name: tenant-infrastructure

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
  name: infrastructure
  namespace: tenant-infrastructure

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: infrastructure
  name: infrastructure-reconciler
  namespace: tenant-infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:tenant-infrastructure:reconciler
- kind: ServiceAccount
  name: infrastructure
  namespace: tenant-infrastructure

