---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: base-fleet-repo
  namespace: gitops-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Foundato/gitops-example-fleet

