---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: appteam
  name: tenant-appteam

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: appteam
  name: appteam
  namespace: tenant-appteam

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: appteam
  name: appteam-reconciler
  namespace: tenant-appteam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:tenant-appteam:reconciler
- kind: ServiceAccount
  name: appteam
  namespace: tenant-appteam

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: appteam
  name: appteam1-test-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: appteam
  name: appteam
  namespace: appteam1-test-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: appteam
  name: appteam-reconciler
  namespace: appteam1-test-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:appteam1-test-ns:reconciler
- kind: ServiceAccount
  name: appteam
  namespace: appteam1-test-ns

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: appteam
  name: appteam1-dev-ns

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: appteam
  name: appteam
  namespace: appteam1-dev-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: appteam
  name: appteam-reconciler
  namespace: appteam1-dev-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:appteam1-dev-ns:reconciler
- kind: ServiceAccount
  name: appteam
  namespace: appteam1-dev-ns

