---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: appteam-tenant-sync
  namespace: gitops-system
spec:
  interval: 2m0s
  path: ./tenants/appteam
  prune: true
  sourceRef:
    kind: GitRepository
    name: base-fleet-repo

