---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tenant-repo
  namespace: tenant-appteam
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/Foundato/gitops-example-tenant

